### ISSUE TITLE
Del is unable to delete the last Option in a Section

### ISSUE THREAD

**Issue by LongHairedHacker** [digineo/go-uci#2]
I just found an off-by-one-error in [Del](https://github.com/digineo/go-uci/blob/master/types.go#L230).

Consider the following Config-snippet from `/etc/config/system`:
```
config timeserver 'ntp'
	option enabled '1'
	option enable_server '0'
	list server '0.lede.pool.ntp.org'
	list server '1.lede.pool.ntp.org'
	list server '2.lede.pool.ntp.org'
	list server '3.lede.pool.ntp.org'
```

When I execute

```go
	r := NewTree("/etc/config")
	r.Del("system", "ntp", "server")
        r.Commit()
```
I expect the all the `list server` options to be be gone. 
However the file `/etc/config/system` remains unchanged.

After some poking, I found an of -by-one-error in [types.go:240](https://github.com/digineo/go-uci/blob/master/types.go#L240).
Slicing a list with `[:l]` where `l` is the length the list returns the same list without changes.
`[:l-1]` is correct.

Moreover I would suggest simplifying the switch statement to `s.Options = append(s.Options[:i], s.Options[i+1:]...)` as it is cleaner, more idiomatic and covers all the cases. 

Arguably it has some performance overhead if the first or last option is deleted (append with empty lists), but I don't think anyone would want to change their configuration frequently enough that it becomes a real problem. (Also I would expect append have its own optimizations for those two corner cases.)

**Comment by dmke** [comment]
I will look at this momentarily. Thanks for bringing this to my attention!

**Comment by dmke** [comment]
Yeah, the `switch` statement was originally a premature optimization—but I agree, performance should not be of much concern here.

I've merged your PR. Thanks again!
