### ISSUE TITLE
ensureConfigLoaded masks errors

### ISSUE THREAD

**Issue by perbu** [digineo/go-uci#20]
The following code is used quite a bit. The problem is that it will mask all sort of errors behind "section not found". It probably not possible to change this without breaking the API, though. Not sure if you want a suggested fix.

```
func (t *tree) ensureConfigLoaded(config string) (*config, bool) {
	cfg, loaded := t.configs[config]
	if !loaded {
		if err := t.loadConfig(config); err != nil {
			return nil, false
		}
		cfg = t.configs[config]
	}
	return cfg, true
}
```

Cheers,

Per.

**Comment by dmke** [comment]
I agree, that bit isn't particularly elegant.

I'm not against breaking the API and build a v2, however I haven't got *any* time for this currently...

**Comment by perbu** [comment]
No problem. I understand you're willing to take patches. I'd be happy to do all the work. We're starting to lean on this code a bit so we wanna give it some love in the months to come.

**Comment by perbu** [comment]
I got something that is starting to look ok. One question is whether or not we wanna keep the deprecated functions or they are to be removed from the v2 package?

If you wanna check out what I've done so far I'll raise a draft PR so you can have a look at the current diff: https://github.com/digineo/go-uci/pull/21

**Comment by dmke** [comment]
I've created a `v2` branch. If you want, you can create a PR against that branch.

**Comment by perbu** [comment]
This is now resolved. Thanks for taking the time to process the patch.
