### ISSUE TITLE
Where is v1.x tag/release?

### ISSUE THREAD

**Issue by adonespitogo** [digineo/go-uci#23]
I can't find the stable v1.x in any releases, branchs or tags.

**Comment by dmke** [comment]
There's no such thing.

The repo was initially created before Go had an understanding for the concept of versions.

If you want to use the pre-v2 code, you can use the master branch:

```console
$ go get github.com/digineo/go-uci@master
go: downloading github.com/digineo/go-uci v0.0.0-20210918132103-37c7b10c14fa
go: added github.com/digineo/go-uci v0.0.0-20210918132103-37c7b10c14fa
```

Please note that the master branch isn't maintained, at all.
