### ISSUE TITLE
Commit() ignores errors

### ISSUE THREAD

**Issue by LongHairedHacker** [digineo/go-uci#4]
Seems like I found another bug.
I've just noticed that in case of an error writing to the config file (e.g. permission problem, out of disk space ...) `Commit()` still returns nil. 

https://github.com/digineo/go-uci/blob/a970c4b2046ecd8d9666b7dacc8f2abb67c480ed/uci.go#L110-L121

It ignores any errors returned by `t.saveConfig(config)`.

I'll have a pull request ready in a few moments.

**Comment by dmke** [comment]
Fixed with #5. Thank you!
